apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: flaskapp
data:
  # FLASK_DEBUG: "false"
  FLASK_DEBUG: "1"
  DB_PORT: "5432"
  DB_NAME: "pg-flaskapp"
  DB_HOST: "postgres-rds.flaskapp.svc.cluster.local"
  DB_USER: "localadmin"
