apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: flaskapp
type: Opaque
data:
  DB_USERNAME: bG9jYWxhZG1pbgo=
  DB_PASSWORD: U3VwZXJTZWNyZXREQlBhc3MyNzMxCg==
  SECRET_KEY: ZGV2LXNlY3JldC1rZXk=
  DATABASE_URL: LmZsYXNrYXBwLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvcG9zdGdyZXMK
